### PR TITLE
Mafalda SFU

### PR DESCRIPTION
**Pull request by piranna**

### CODE REVIEW

**Comment by webRTCv1** [comment]
Hi piranna,

I hope you're doing well! Big thanks for your recent pull request. Mafalda SFU it's really caught our eye.

We noticed it uses mediasoup, a tech we're big fans of. So, we're thinking Mafalda SFU could be a great fit in our Media Servers section. Could you please moving it there?

We're all about open-source projects, and Mafalda SFU looks promising, even if we don't find its repo (source code) on github. It could be cool to see how it works with other projects like Edumeet or even better on MiroTalk SFU. Exploring that could give us some insights into how practical and useful it might be.

Thanks a bunch for your work on this.

Cheers!

**Comment by piranna** [comment]
> Mafalda SFU it's really caught our eye.

Glad you like it :-)


> We noticed it uses mediasoup, a tech we're big fans of. So, we're thinking Mafalda SFU could be a great fit in our Media Servers section. Could you please moving it there?

Yes, it uses Mediasoup, although not sure if it should go to the Media Servers section. What Mafalda SFU does, it's a wrapper on top of Mediasoup that offers the same API, but internally manages the vertical and horizontal scalability, so yeah, it should go to the same section where Mediasoup is, but the fact is that Mediasoup should not be considered as a media server by itself because it works mostly as a library... so in fact, it's Mediasoup the one that should be in the SFU category, meanwhile EduMeet or Jitsy should be in the Media Servers section... What do you think?

Said that, `Remote-Mediasoup-server` could be considered a media server itself, since it's a standalone process offering a WebSockets API, just only that's not intended to be used by clients but instead but by tools or app servers.


> We're all about open-source projects, and Mafalda SFU looks promising, even if we don't find its repo (source code) on github. It could be cool to see how it works with other projects like Edumeet or even better on MiroTalk SFU. Exploring that could give us some insights into how practical and useful it might be.

Mafalda SFU is closed source, although some parts are open source. I have been suggested to open source some parts of it, still considering about that. You have some documentation on the project website, but meanwhile I'm writing some drafts about how it works to be published soon. Also I have a pending article about how to migrate EduMeet to use it (spoiler: 5 minutes of work, and less than 25 lines of code :-) ), but didn't know about MiroTalk, definitely something to look for, thanks! :-D

**Comment by webRTCv1** [comment]
> Yes, it uses Mediasoup, although not sure if it should go to the Media Servers section. What Mafalda SFU does, it's a wrapper on top of Mediasoup that offers the same API, but internally manages the vertical and horizontal scalability, so yeah, it should go to the same section where Mediasoup is, but the fact is that Mediasoup should not be considered as a media server by itself because it works mostly as a library... so in fact, it's Mediasoup the one that should be in the SFU category, meanwhile EduMeet or Jitsy should be in the Media Servers section... What do you think?

We concur that relocating MediaSoup alongside Mafalda SFU in the Library section is appropriate. Considering that EduMeet and Jitsi are WebRTC applications utilizing SFU technology, we believe their current placement is fitting.

> Mafalda SFU is closed source, although some parts are open source. I have been suggested to open source some parts of it, still considering about that. You have some documentation on the project website, but meanwhile I'm writing some drafts about how it works to be published soon.

Although Mafalda SFU seems like an excellent product to us, and we are eager to see it in action. the reason we are aiming for Open Source here and not for Closed Source are the following: 

---

1. **Lack of Transparency:** Closed source software is not transparent in terms of its source code. Users cannot access or review the code to understand how the software functions. This lack of transparency can raise concerns about security, privacy, and potential vulnerabilities.

---

2. **Vendor Lock-In:** Users of closed source software are often tied to the vendor for updates, bug fixes, and support. This can result in a form of vendor lock-in, where it becomes difficult to switch to an alternative solution without significant challenges and costs.

---

3. **Limited Customization:** Users have limited or no ability to modify the software to suit their specific needs. Customization options are typically restricted to what the vendor provides, limiting the adaptability of the software to unique requirements.

---

4. **Dependency on Vendor:** Users are dependent on the vendor for updates, support, and enhancements. If the vendor decides to discontinue the software or goes out of business, users may face challenges in maintaining and supporting their systems.

---

5. **Costs:** Closed source software often involves licensing fees, which can be a significant cost for businesses and organizations. Additionally, the costs may include fees for support, updates, and additional features.

---

6. **Security Concerns:** The closed nature of the source code can make it more challenging to identify and fix security vulnerabilities. Users are reliant on the vendor to promptly address security issues, and there may be a delay in receiving patches or updates.

---

7. **Limited Innovation:** Innovation and improvements are solely driven by the vendor. Users may have limited influence on the development direction of the software, and updates are subject to the vendor's priorities and timelines.

---

8. **Incompatibility with Open Source:** Closed source software may be incompatible with open-source solutions or standards, limiting interoperability and collaboration with other software or systems.

---

9. **Restrictions on Use:** Closed source licenses often come with restrictions on how the software can be used or deployed. This can limit flexibility and may be a concern for users with specific usage requirements.

---

10. **Uncertainty in the Long Term:** There may be concerns about the long-term viability of closed source software. If a vendor discontinues a product, users may be left without ongoing support or updates, potentially leading to security and compatibility issues.

---

> Also I have a pending article about how to migrate EduMeet to use it (spoiler: 5 minutes of work, and less than 25 lines of code :-) ), but didn't know about MiroTalk, definitely something to look for, thanks! :-D

In our investigation, we discovered that both Edumeet and MiroTalk SFU leverage the outstanding mediasoup library. However, while EduMeet is a commendable project, MiroTalk SFU stands out as a relatively novel entrant in the field, boasting advanced and innovative features. With an tones of functionalities, MiroTalk SFU has captured our attention and become one of our preferred choices, aligning seamlessly with our frequent usage patterns. We believe that the incorporation of Mafalda SFU could propel it to a revolutionary step forward, further enhancing its capabilities and solidifying its position as a cutting-edge solution, as well as giving even more visibility to Mafalda SFU!

**Comment by piranna** [comment]
> We concur that relocating MediaSoup alongside Mafalda SFU in the Library section is appropriate.

Ok, should I move them, then?


> Considering that EduMeet and Jitsi are WebRTC applications utilizing SFU technology, we believe their current placement is fitting.

That's not like that... EduMeet is a videoconference app, the same as OpenVidu, the fact they use a SFU is an implementation detail. In fact, OpenVidu started build on top of Kurento, that's a MCU. OTOH, Jitsi is a suite of packages, not just only a media server but a full technology stack itself.


> Although Mafalda SFU seems like an excellent product to us, and we are eager to see it in action. the reason we are aiming for Open Source here and not for Closed Source are the following:

I'm a proud advocate of Open Source and Open Standards myself, Mafalda is in fact the first product I'm developing closed source because it got a lot of commercial interest on its beginning. Regarding your points, I agree on most of them regarding Mafalda SFU, except for the **Vendor Lock-In** and **Incompatibility with Open Source** points, since Mafalda SFU have by design the same API of Mediasoup, so you can migrate both directions at any time.


> We believe that the incorporation of Mafalda SFU could propel it to a revolutionary step forward, further enhancing its capabilities and solidifying its position as a cutting-edge solution, as well as giving even more visibility to Mafalda SFU!

Definitely, I think so too :-)

**Comment by webRTCv1** [comment]
While the most fitting category for Mafalda SFU would be in the libraries section alongside mediasoup, our repository aims to gather all **open source projects** associated with WebRTC. We appreciate Mafalda SFU, but given its **closed-source** nature, we are uncertain if it aligns with the repository's intent. If there is any interest or potential in the future to open source Mafalda SFU, we would gladly welcome its inclusion here with enthusiasm!

**Comment by piranna** [comment]
I think It would make sense to have a Showcase of both open and closed source project, cleirly identifying them. There are no so much of any of them in any case.

**Comment by webRTCv1** [comment]
> I think It would make sense to have a Showcase of both open and closed source project, cleirly identifying them. There are no so much of any of them in any case.

Our fundamental mission of this repository is to meticulously curate an expansive collection of `exclusively open-source projects`, ensuring accessibility to the broader community. These projects stand as invaluable educational assets, empowering developers to refine their skills and actively contribute to the ongoing enhancement of these cutting-edge initiatives. Our overarching objective is to streamline the maintenance process by establishing a repository renowned for its top-tier projects, capable of competing with `closed-source counterparts` in prominent sectors such as Google Meet, Zoom, Teams, and other industry leaders.

We firmly believe that GitHub is best suited for open-source projects. Otherwise, it would risk transforming into an `advertising space`.

**Comment by piranna** [comment]
I think you are confusing closed source / privative, with online silos, that are the real cáncer of Tech stacks today...

**Comment by webRTCv1** [comment]
Given your enthusiasm for WebRTC and your contributions to open-source projects, we'd like to make a special exception for you. Feel free to relocate Mafalda SFU under the **Libraries** category,  and we are enthusiastic about the prospect of continuing this journey together. 😉

**Comment by piranna** [comment]
> Given your enthusiasm for WebRTC and your contributions to open-source projects, we'd like to make a special exception for you. Feel free to relocate Mafalda SFU under the **Libraries** category, and we are enthusiastic about the prospect of continuing this journey together. 😉

Done, also moved `Mediasoup` there.

For easier maintability, it should be changed for a Markdown table, it's easier to modify and update...

**Pull request merged**
